

import { ScrollArea } from "@radix-ui/react-scroll-area";
export const metadata = {
  title: "About MSNS",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "https://pern-my.sharepoint.com/:i:/g/personal/20011556-085_uog_edu_pk/ES_o1KrfBLpLkrocXkQMqpoBzv4pgNIKc_RY9Vlpp3ByZA?e=7GC16Y" }],
};

export default function AboutLayout({children}: { children: React.ReactNode }) {
  return (
    <body>
      <ScrollArea className="ml-10 mt-4 rounded-lg bg-emerald-200 p-4 shadow-md">
        {children}
      </ScrollArea>
    </body>
  );
}
