



import { ScrollArea } from "@radix-ui/react-scroll-area";
export const metadata = {
  title: "About MSNS",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "https://asset.cloudinary.com/dvvbxrs55/34f0d2cd0ac3f8ba5083649ca225e6f6" }],
};

export default function AboutLayout({children}: { children: React.ReactNode }) {
  return (
    <body>
      <ScrollArea className="ml-10 mt-4 rounded-lg bg-emerald-200 p-4 shadow-md">
        {children}
      </ScrollArea>
    </body>
  );
}
