

import { ScrollArea } from "@radix-ui/react-scroll-area";
import { Sidebar } from "lucide-react";
export const metadata = {
  title: "About MSNS",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/logo/logo-white.png" }],
};

export default function AboutLayout({children}: { children: React.ReactNode }) {
  return (
    <body>
      <Sidebar />
      <ScrollArea className="ml-10 mt-4 rounded-lg bg-emerald-200 p-4 shadow-md">
        {children}
      </ScrollArea>
    </body>
  );
}
