import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { TRPCReactProvider } from "~/trpc/react";
import { Footer } from "./_components/footer/footer";
import { ScrollArea } from "~/components/ui/scroll-area";
export const metadata = {
  title: "MSNS-LMS",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/logo/logo-white.png" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex flex-col min-h-screen">
      <ScrollArea>
        <TRPCReactProvider>{children}</TRPCReactProvider>
        </ScrollArea>
      </body>
      <Footer />
    </html>
    
  );
}
