import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { TRPCReactProvider } from "~/trpc/react";
import { Footer } from "./_components/footer/footer";
import { ScrollArea } from "~/components/ui/scroll-area";
import StickyHeader from "./_components/shared/elements/StickyHeader";
export const metadata = {
  title: "MSNS-LMS",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "https://asset.cloudinary.com/dvvbxrs55/328659a69b60f3ba7525d7efdffefa70" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex min-h-screen flex-col">
        <ScrollArea>
          <StickyHeader />
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </ScrollArea>
        <Footer />
      </body>
    </html>
  );
}
